#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TF_discreta.Resource", IsApplication=true)]

namespace TF_discreta
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040010
			public const int Elements = 2130968592;
			
			// aapt resource value: 0x7f040013
			public const int GoBack = 2130968595;
			
			// aapt resource value: 0x7f04000e
			public const int TextCant = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int TextElement = 2130968591;
			
			// aapt resource value: 0x7f040001
			public const int add = 2130968577;
			
			// aapt resource value: 0x7f04000b
			public const int button1 = 2130968587;
			
			// aapt resource value: 0x7f040004
			public const int buttonnext = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int comp = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int container = 2130968579;
			
			// aapt resource value: 0x7f04000d
			public const int enumtext = 2130968589;
			
			// aapt resource value: 0x7f040009
			public const int linearLayout1 = 2130968585;
			
			// aapt resource value: 0x7f040014
			public const int madre = 2130968596;
			
			// aapt resource value: 0x7f040012
			public const int matriz = 2130968594;
			
			// aapt resource value: 0x7f040011
			public const int matrizenum = 2130968593;
			
			// aapt resource value: 0x7f040005
			public const int nombre2 = 2130968581;
			
			// aapt resource value: 0x7f04000c
			public const int relativ = 2130968588;
			
			// aapt resource value: 0x7f040007
			public const int remove = 2130968583;
			
			// aapt resource value: 0x7f040000
			public const int text = 2130968576;
			
			// aapt resource value: 0x7f04000a
			public const int textView1 = 2130968586;
			
			// aapt resource value: 0x7f040002
			public const int textin = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int textout = 2130968584;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Adding = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int buttons = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int fila = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Main = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Showing = 2130837508;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
